# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/学习资料/DL-Kit/HDL_Framework/GenshinKitchen.srcs/sources_1/bd/pll108MHz/ip/pll108MHz_clk_wiz_0_0_1/pll108MHz_clk_wiz_0_0.xci
# IP: The module: 'pll108MHz_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/学习资料/DL-Kit/HDL_Framework/GenshinKitchen.srcs/sources_1/bd/pll108MHz/ip/pll108MHz_clk_wiz_0_0_1/pll108MHz_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll108MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/学习资料/DL-Kit/HDL_Framework/GenshinKitchen.srcs/sources_1/bd/pll108MHz/ip/pll108MHz_clk_wiz_0_0_1/pll108MHz_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll108MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/学习资料/DL-Kit/HDL_Framework/GenshinKitchen.srcs/sources_1/bd/pll108MHz/ip/pll108MHz_clk_wiz_0_0_1/pll108MHz_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll108MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/学习资料/DL-Kit/HDL_Framework/GenshinKitchen.srcs/sources_1/bd/pll108MHz/ip/pll108MHz_clk_wiz_0_0_1/pll108MHz_clk_wiz_0_0.xci
# IP: The module: 'pll108MHz_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/学习资料/DL-Kit/HDL_Framework/GenshinKitchen.srcs/sources_1/bd/pll108MHz/ip/pll108MHz_clk_wiz_0_0_1/pll108MHz_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll108MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/学习资料/DL-Kit/HDL_Framework/GenshinKitchen.srcs/sources_1/bd/pll108MHz/ip/pll108MHz_clk_wiz_0_0_1/pll108MHz_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll108MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/学习资料/DL-Kit/HDL_Framework/GenshinKitchen.srcs/sources_1/bd/pll108MHz/ip/pll108MHz_clk_wiz_0_0_1/pll108MHz_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll108MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
